"""empty message

Revision ID: 2813a2948bf6
Revises: 27651f4c33d7
Create Date: 2025-07-05 23:17:27.321901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2813a2948bf6'
down_revision = '27651f4c33d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrada', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
