"""empty message

Revision ID: 8fee4393d9cd
Revises: 2813a2948bf6
Create Date: 2025-07-05 23:30:32.895080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fee4393d9cd'
down_revision = '2813a2948bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autor', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('entrada_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['autor'], ['id'])
        batch_op.drop_column('autor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entrada_ibfk_1'), 'user', ['autor_id'], ['id'])
        batch_op.drop_column('autor')

    # ### end Alembic commands ###
