"""Renombrar comments a content en Comment

Revision ID: bc8e674f0340
Revises: 72ff748e154a
Create Date: 2025-10-24 20:14:29.098701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc8e674f0340'
down_revision = '72ff748e154a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.drop_column('comments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', mysql.TEXT(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
