"""empty message

Revision ID: c1677ea55ceb
Revises: 8fee4393d9cd
Create Date: 2025-07-05 23:42:10.684357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1677ea55ceb'
down_revision = '8fee4393d9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autor_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('entrada_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['autor_id'], ['id'])
        batch_op.create_foreign_key(None, 'categoria', ['categoria_id'], ['id'])
        batch_op.drop_column('autor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autor', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entrada_ibfk_1'), 'user', ['autor'], ['id'])
        batch_op.drop_column('categoria_id')
        batch_op.drop_column('autor_id')

    # ### end Alembic commands ###
